trigger:
  branches:
    include:
      - develop
      - master

pr:
  branches:
    include:
      - develop
      - master

variables:
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - name: testProjectPath
    value: './AzureDevOpsArtifacts.Tests/AzureDevOpsArtifacts.Tests.csproj'
  - name: nugetProjectPath
    value: './AzureDevOpsArtifacts/AzureDevOpsArtifacts.csproj'
  - name: solutionProjectPath
    value: './AzureDevOpsArtifacts.sln'

stages:
  - stage: 'Build_Test'
    jobs:
      - job: "Build"
        displayName: 'Build and Test'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - template: azure-pipelines-template.yml
