trigger:
  branches:
    include:
      - develop
      - master

pr:
  branches:
    include:
      - develop
      - master

variables:
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - name: testProjectPath
    value: './AzureDevOpsArtifacts.Tests/AzureDevOpsArtifacts.Tests.csproj'
  - name: nugetProjectPath
    value: './AzureDevOpsArtifacts/AzureDevOpsArtifacts.csproj'
  - name: solutionProjectPath
    value: './AzureDevOpsArtifacts.sln'
  - name: nugetFeedId
    value: '04c81209-5ca9-4784-b02b-bdd6e2024216/d4626246-960c-4423-b417-81d62a12eebc'

stages:
  - stage: 'Build_Test'
    jobs:
      - job: "Build"
        displayName: 'Build and Test'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - template: azure-pipelines-template.yml
